const { readFileSync } = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const code = readFileSync(require('node:path').join(__dirname, '../theme.js'), 'utf8');
function setup({ saved = null, dark = false, blocked = false } = {}) {
    const events = {}, windowEvents = {}, clicks = {};
    const toggle = { hidden: true, setAttribute(k,v) { this[k] = v; }, addEventListener(k, fn) { clicks[k] = fn; } };
    const system = { matches: dark, addEventListener(k, fn) { this.change = fn; } };
    const root = { dataset: {} };
    const storage = { value: saved, getItem() { if (blocked) throw Error('blocked'); return this.value; }, setItem(k,v) { if (blocked) throw Error('blocked'); this.value = v; } };
    vm.runInNewContext(code, { window: { matchMedia: () => system, addEventListener(k,fn) { windowEvents[k] = fn; } }, document: { documentElement: root, querySelector: () => toggle, addEventListener(k,fn) { events[k] = fn; } }, localStorage: storage });
    events.DOMContentLoaded();
    return { root, toggle, storage, system, clicks, windowEvents };
}
let app = setup({ dark: true });
assert.equal(app.root.dataset.theme, 'dark');
assert.equal(app.toggle.hidden, false);
assert.equal(app.toggle['aria-pressed'], 'true');
app.system.matches = false; app.system.change();
assert.equal(app.root.dataset.theme, 'light');
app.clicks.click();
assert.equal(app.root.dataset.theme, 'dark');
assert.equal(app.storage.value, 'dark');
app.system.change();
assert.equal(app.root.dataset.theme, 'dark');
app = setup({ saved: 'light', dark: true });
assert.equal(app.root.dataset.theme, 'light');
app.windowEvents.storage({ key: 'mangan-tako-theme', newValue: 'dark' });
assert.equal(app.root.dataset.theme, 'dark');
app.windowEvents.storage({ key: null, newValue: null });
app.system.matches = false; app.system.change();
assert.equal(app.root.dataset.theme, 'light');
app = setup({ saved: 'invalid', dark: true });
assert.equal(app.root.dataset.theme, 'dark');
app = setup({ blocked: true });
app.clicks.click();
assert.equal(app.root.dataset.theme, 'dark');
assert.equal(app.toggle['aria-pressed'], 'true');
app.clicks.click();
assert.equal(app.root.dataset.theme, 'light');
console.log('PASS: system theme, persistence, explicit preference, storage synchronization, invalid/blocked storage, and toggle state');
